Classes/Driver/AmazonS3Driver.php

Fixes https://forge.typo3.org/issues/76380.
The original pull request was https://github.com/TYPO3-extensions/aus_driver_amazon_s3/pull/1  by onigunn and you commented to please use the correct repository. Since there was no feedback to this issue and we needed that function for our client here is the pull request in the correct repo i hope

[TASK] Implement replaceFile method

---

Classes/Driver/AmazonS3Driver.php

add $numberOfItems to getFilesInFolder function

add limit to getFilesInFolder function

---

Classes/Driver/AmazonS3Driver.php
Resources/Private/PHP/Aws/aws-autoloader.php
composer.json

* Assume root folder for emtpy identifier
* Enforce trailing slash for processing folder
* Fix autoloading fatal error in non composer mode

Fix incompatibilities with current TYPO3 versions

---

Classes/Driver/AmazonS3Driver.php

in `AmazonS3Driver->getFileInfoByIdentifier()`
the parameter `$propertiesToExtract` was ignored. That led
`typo3/sysext/core/Classes/Resource/AbstractFile.php getSize()`
to always return the storageUid instead of the correct size.

[BUGFIX] use the parameter in getFileInfoByIdentifier() 

---

Classes/Driver/AmazonS3Driver.php

adds a very basic implementation to allow forceDownload and for example the use of fal_securedownload

[TASK] implement dumpFileContents() to allow forceDownload

---

Classes/Driver/AmazonS3Driver.php

That allow processing temporary file before they will be prossed in graphic functions.

Added SignalSlotDispatcher in the getFileForLocalProcessing function.

---

ext_localconf.php

TYPO3 extensions must not use the DriverRegistry to register
their driver implementations. See the TYPO3 coredev channel message
https://typo3.slack.com/archives/C03AM9R17/p1538658116000100
for more information.

[BUGFIX] Register the driver via $GLOBALS

---

Classes/Driver/AmazonS3Driver.php
Classes/S3Adapter/MultipartUploaderAdapter.php

Empty files cannot be created with MultpartUploader.
Also, when an error occurs in the MultipartUploader, the MultipartUploadAdapter will retry the upload forever. This might be useful for temporary errors like Network problems, but blocks a PHP process and creates high server load for permanent errors (like the one with the empty files)
This patch
- Fixes the upload error by creating the file directly instead
- Introduces a retry limit and aborts the upload if too many errors occur
I'm not sure if MAX_RETRIES = 10 is appropriate, but in my tests I didn't need a single retry even when uploading big files.

MultipartUploader fails to upload empty files

---

Classes/Driver/AmazonS3Driver.php
Configuration/FlexForm/AmazonS3DriverFlexForm.xml
Resources/Private/Language/locallang_flexform.xlf

These patches add support for S3-compatible storage services like https://min.io/ and fix a bug when creating folders on a minio backend ("XMinioObjectExistsAsDirectory / Object name already exists as a directory.").
It also adds a description for the public base URL field so people see that the protocol may not be entered there.
Resolves: https://github.com/andersundsehr/aus_driver_amazon_s3/issues/62
It includes the commit for pull request #83, because performance is abysmal without it.
Given that minio is running on port 9000 and that the bucket is publicly accessible (`mc policy set download minio/typo3`)
- bucket: typo3
- region: any (will be ignored)
- customHost: http://minio:9000
- pathStyleEndpoint: true
- key: your read-write access key
- secretKey: your read-write password
- …

Support MinIO storage backend

---

Classes/Driver/AmazonS3Driver.php

Methods prefixExists() and isFolderEmpty() both use getListObjects()
with the "MaxKeys: 1" argument.
If the directory contains more than one file, the API says the result is
truncated (which we wanted!), which causes getListObjects() to load all
objects in the folder.
This patch checks if the MaxKeys argument was provided, and prevents
loading the truncated objects in that case.
On S3 this happens when using a bucket that has no special "folder objects"
(which are created by aus_driver_amazon_s3).
With MinIO it always happens, because HEAD requests fail for non-empty folders,
and thus listObjects is always used.

[BUGFIX] Respect "MaxKeys" setting when listing objects

---

Classes/Driver/AmazonS3Driver.php

.. instead of throwing a generic \Exception.
\TYPO3\CMS\Core\Resource\Driver\LocalDriver (TYPO3 v10.4) already
throws that exception class when a file does not exist.
Other extensions like VHS depend on that behavior, because they catch
those exceptions to specifically handle the file-not-found case.
Also mention the name of the missing file in the exception message
to ease debugging.
Related: https://github.com/FluidTYPO3/vhs/issues/1725

[BUGFIX] Throw \InvalidArgumentException when a file does not exist.

---

Classes/Driver/AmazonS3Driver.php

If the credentials array-key exists in the configuration, the AWS SDK will always try to use that, even if key and secret are empty. By removing the credentials key completely, the S3 client will fall back to other authentication options: 
1. Load credentials from environment variables.
2. Load credentials from a credentials .ini file.
3. Load credentials from an IAM role
See: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#credentials

Set credentials only if provided in the storage configuration

---

Classes/Driver/AmazonS3Driver.php
Classes/Service/CompatibilityService.php
composer.json
ext_emconf.php
ext_localconf.php

.. while keeping compatibility with TYPO3 v10.4.11+
This obsoletes #109, #112 and #117.

Fix some deprecated code

---

Classes/Driver/AmazonS3Driver.php

I cannot remember under which circumstances the storage was not yet initialized before it was used in getFolder(), but it surely is not bad to make sure it gets loaded when needed.

[BUGFIX] Make sure storage is loaded before accessing it

---

Classes/Service/CompatibilityService.php

The two methods that currently use `isBackend()` expect `$_GET` to contain stuff when `isBackend()` returns true. This is unlikely to be the case in CLI mode.

[BUGFIX] Properly distinguish CLI and backend mode

---

Classes/Driver/AmazonS3Driver.php

Instead of passing the folder path (identifier) to the deleteFolder() method, the object of the subfolder was passed.
This led to the exception "Instances of Aws\S3\S3Client cannot be serialized".
Test:
1. Create folder "subfolder1"
2. Within "subfolder1", create "subfolder2"
3. Upload a file into "subfolder2"
4. Delete "subfolder1".

[BUGFIX] Fix deleting folders with subfolders

---

Classes/Driver/AmazonS3Driver.php

TYPO3 v12 file list wants it
Part of: https://github.com/andersundsehr/aus_driver_amazon_s3/issues/135

[BUGFIX] Return dummy "mtime" attribute for folders

---

Classes/Driver/AmazonS3Driver.php

The TYPO3 indexer in
`sysext/core/Classes/Resource/Index/Indexer.php#gatherFileInformationArray`
calls "getFileInfoByIdentifier" with an empty "$propertiesToExtract" array, which means it wants to have all information.
S3 driver did not yet return the mime type in that case, causing a crash:
> PHP Warning: Undefined array key "mime_type"
> in typo3/sysext/core/Classes/Resource/Index/Indexer.php line 323
So instead of only fetching the MIME type when it is explicitly requested, we also fetch it when no property has been given.
The error occured when a file was not in sys_file but already existed in storage - e.g. when the storage had been filled outside of TYPO3.

[BUGFIX] Make sure mime type is available when no property is specified

---

Classes/Driver/AmazonS3Driver.php

At least MinIO's list response does not contain a 'Content' property when a folder has no child elements.
When moving a folder, check for its existence before iterating over it.
Resolves: https://github.com/andersundsehr/aus_driver_amazon_s3/issues/148

[BUGFIX] Do not crash when moving empty folder

---

Classes/Service/MetaDataUpdateService.php

derived from https://github.com/andersundsehr/aus_driver_amazon_s3/pull/136/files
But with strict comparion and removed the non-necessary $imageDimensions !== null which is alwas true.

[BUGFIX] Create metadata record if needed

---

.git-blame-ignore-revs

This shows the real change commit when running "git blame" instead of showing the commit where the code style was changed.
This needs to be enabled on a per-checkout basis with
$ git config blame.ignoreRevsFile .git-blame-ignore-revs
See
https://git-scm.com/docs/git-config#Documentation/git-config.txt-blameignoreRevsFile

[TASK] Ignore Code style fixes/reformattings in "git blame"

---

Classes/Driver/AmazonS3Driver.php
Makefile
README.md

When having multiple S3-based storages in TYPO3, the file tree view shows the same folders for all storages since commit
> 6d01c1abea2741692a5254ce487ed007eaebfebd
> Make some caches configurable, fixes a caching issue
> and minor performance improvements
The culprit is that the caching layer does not take the bucket configuration into account, leading to the same cache key "/" for all storages.
This commit uses the S3 client endpoint as prefix for all cache keys.

[BUGFIX] Use different cache keys for different bucket URLs

---

Classes/Driver/AmazonS3Driver.php
Makefile
README.md
Tests/Functional/Driver/AmazonS3DriverTest.php

This patch fixes the problem that fetching a folder via API and using that to upload a file put the file into the wrong folder:
$folder = $storage->getFolder('myfolder');
$storage->addFile('/tmp/file.txt', $folder, 'file.txt');
//created "/myfolderfile.txt" instead of "/myfolder/file.txt"
TYPO3's own
`AbstractHierarchicalFilesystemDriver::canonicalizeAndCheckFolderIdentifier` appends slashes,
and our `createFolder()` already returned identifiers with slashes at the end.
Resolves: https://github.com/andersundsehr/aus_driver_amazon_s3/issues/146

[BUGFIX] Append slash to folder identifiers

---

Classes/S3Adapter/MetaInfoDownloadAdapter.php

The current TYPO3 version 12.4.32 introduces a standard mime type guesser, which is called by the S3 adapter. Previously, the adapter was passed as an object, but the mime type guesser expects an SpFileInfo object.
In this correction, the hook is now called with a TYPO3 FileInfo object, which is created with the base name of the S3 object.

[FIX] Call mime type guesser hooks with FileInfo object

---

Classes/Index/Extractor.php
README.md
Tests/Unit/S3Adapter/MetaInfoDownloadAdapterTest.php
composer.json

Fixes Issue https://github.com/andersundsehr/aus_driver_amazon_s3/issues/156
also getImageDimensionsOfRemoteFile is called twice with the same identifier, so singleton provides a small "runtime cache"

Fix growing var/transient folder contents to get (image) sizes
